site: Heypenny

title: Heypenny
email: support@moelten.io
baseurl: ""
url: https://heypenny.moelten.io
domain: heypenny.moelten.io

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  photoshoots:
    output: true
    permalink: /photos/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "photoshoots"
    values:
      layout: "photoshoot"

include:
  - ".well-known"

exclude:
  - renovate.json
  - README.md

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-figure

paginate: 6
paginate_path: "/blog/page:num/"
