[[redirects]]
from = "/community"
to = "https://discord.gg/HAPJm87mdW"
status = 302
force = true

[[redirects]]
from = "/coaster"
to = "/?r=coaster"
status = 302
force = true

[[redirects]]
from = "/a/static/*"
to = "https://us-assets.i.posthog.com/static/:splat"
host = "us-assets.i.posthog.com"
status = 200
force = true

[[redirects]]
from = "/a/*"
to = "https://us.i.posthog.com/:splat"
host = "us.i.posthog.com"
status = 200
force = true
