basic_settings:
  site_title: Heypenny
  site_tagline: >-
    A mobile app to reduce financial stress among friends.

menu_settings:
  menu_items:
    - title: 'Contact us'
      url: '/contact'
    - title: 'Community'
      url: '/community'
